PROGRAM Montecarlo_s
	IMPLICIT NONE
	INTEGER (KIND = 16) :: I, LIM
	REAL :: PI, X, Y, RLIM, COUN
	PI = 0
	COUN = 0
	LIM = 2147483647
	RLIM = 2147483647.0
	DO I = 1, LIM
		CALL RANDOM_NUMBER(X)
		CALL RANDOM_NUMBER(Y)
		IF( X*X + Y*Y < 1) THEN
			COUN = COUN + 1
		END IF
	END DO	
	PI = 4.0 * COUN / RLIM
	PRINT *, PI
END PROGRAM Montecarlo_s
