PROGRAM Montecarlo_p
	IMPLICIT NONE
	INTEGER (KIND = 16) :: I, LIM
	REAL :: PI, X, Y, RLIM, COUN
	PI = 0
	COUN = 0
	LIM = 2147483647
	RLIM = 2147483647.0
	CALL OMP_SET_NUM_THREADS(16) 
	!$OMP PARALLEL
	DO I = 1, LIM
		CALL RANDOM_NUMBER(X)
		CALL RANDOM_NUMBER(Y)
		IF( X*X + Y*Y < 1) THEN
		!$OMP ATOMIC 
			COUN = COUN + 1
		END IF
	END DO	
	!$OMP END PARALLEL
	PI = 4.0 * COUN / RLIM
	PRINT *, PI
END PROGRAM Montecarlo_p
