FUNCTION F(X)
	REAL(KIND = 16) :: F, X
	INTEGER (KIND = 16) :: I
	F = 0
	DO I = 0, INT(X)
		F = F + I
	END DO
	RETURN
END FUNCTION F 


FUNCTION TRAP(A, B, H)
	REAL (KIND = 16) :: TRAP, A, B, H, F
	TRAP = (F(A) + F(B))*H
	RETURN
END FUNCTION

PROGRAM Trap_s
	IMPLICIT NONE
	INTEGER (KIND = 16) :: I, SUMS
	REAL (KIND = 16) :: N, H, TRAP
	REAL (KIND = 16), DIMENSION (201) :: MESH
	SUMS = 0
	N = 200
	H = 100000000/N
	DO I = 0, INT(N)
		MESH(I) = H*I
	END DO	
	DO I = 0, INT(N)
		SUMS = SUMS + TRAP(MESH(I), MESH(I+1), H)
	END DO
	PRINT *, SUMS

END PROGRAM Trap_s
